// generated by halo_serdes.dsp.fixed_datapath.dump_sv_package
localparam int N = 2000;
localparam int N_OUT = 1985;
localparam int NF = 15;
localparam int ND = 1;
localparam int NL = 4;
localparam int N_PRE = 4;
localparam int FFE_SHIFT = 4;
localparam int DFE_SHIFT = 8;
localparam int OUT_BITS = 12;
localparam int DO_ROUND = 1;
localparam int CW = 32;
