// generated by halo_serdes.dsp.fixed_mlsd.dump_mlsd_vectors
localparam longint N = 4000;
localparam longint NL = 4;
localparam longint SEQ_LEN = 4;
localparam longint MARGIN = 300;
localparam longint SQ_SHIFT = 4;
localparam longint METRIC_MAX = 262143;
localparam longint PASSES = 2;
localparam longint CW = 64;
