// generated by halo_serdes.dsp.fixed_viterbi.dump_viterbi_vectors
localparam longint N = 3000;
localparam longint NL = 4;
localparam longint NS = 16;
localparam longint SQ_SHIFT = 3;
localparam longint METRIC_MAX = 1048575;
localparam longint CW = 64;
